# Generated by Django 4.2.1 on 2023-06-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancodados', '0004_usuario_email_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('descricao', models.TextField(blank=True, max_length=50)),
                ('preco', models.FloatField(null=True)),
                ('categoria', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
